#!/usr/bin/env bash                                                                                                            
#stop me if you can
trap 'echo "I am invincible!!!"' SIGTERM
i=1
while [ $i -gt 0 ]
do 
echo "To infinity and beyond"
sleep 2
done
